title: iboB
author: Borislav Stanimirov
email: b.stanimirov@abv.bg
description: >-
  Homepage of Borislav Stanimirov (aka iboB). Programmer.
baseurl: ""
url: "ibob.github.io"  # do I need this?
twitter_username: stanimirovb
github_username:  iboB

# page settings
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE.txt

future: true # allow the publishing of posts in the future
